# 1  Build Angular app
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

#  2 Serve using Nginx
FROM nginx:alpine

# COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/dist/angular-15-crud /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]